cache:
  paths:
    - frontend/dist/frontend

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - build
  - release
  - deploy
#  - notify

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  # переменные CI_REGISTRY_USER, CI_REGISTRY_PASSWORD, CI_REGISTRY генерятся Гитлабом, их задавать не надо
  script:
    - echo "Build Dockerfile frontend"
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/frontend"
      --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/sausage-frontend:$CI_COMMIT_SHA"
      --build-arg VERSION=$VERSION
      --cache=true

release:
  variables:
    GIT_STRATEGY: none
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  cache: [ ]
  stage: release
  before_script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - crane tag $CI_REGISTRY_IMAGE/sausage-frontend:$CI_COMMIT_SHA $VERSION

deploy-frontend:
  stage: deploy
  image: alpine:3.18
  before_script:
    - apk add openssh-client bash gettext docker-cli
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan ${DEV_HOST} >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - envsubst < ./frontend/docker-compose-frontend.yml > docker-compose-temp.yml
    - scp docker-compose-temp.yml ${DEV_USER}@${DEV_HOST}:~/docker-compose-frontend.yml
    - ssh ${DEV_USER}@${DEV_HOST} "mkdir -p ~/templates"
    - scp -r ./frontend/templates/ ${DEV_USER}@${DEV_HOST}:~/templates/
    - envsubst < ./frontend/deploy-frontend.sh|ssh ${DEV_USER}@${DEV_HOST}
  after_script:
    - rm -f docker-compose-temp.yml

#telegram-notification-frontend:
#  stage: notify
#  rules:
#    - changes:
#      - frontend/**/*
#    - if: '$CI_COMMIT_MESSAGE =~ /send notification/i'
#      when: always
#    - when: never
#  script:
#    - |
#      curl -s -X POST -H "Content-Type: application/json" \
#      -d '{"chat_id": "-1002426676593", "text": "✅ Быковский Д.В. Frontend успешно собран! Ссылка на артефакт: '$CI_PROJECT_URL'/-/jobs/artifacts/'$CI_COMMIT_SHA'/download?job=build-frontend-code-job"}' \
#      "https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage"