cache:
  paths:
    - frontend/dist/frontend

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  SONAR_FRONT_OPTS: "-Dsonar.projectKey=dby_key_front -Dsonar.sources=frontend/src -Dsonar.host.url=${SONARQUBE_URL} -Dsonar.login=${SONAR_PROJECT_KEY_FRONT}"

stages:
  - build
  - test
  - release
  - deploy
  - notify

build:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build
  only:
    changes:
      - frontend/**/*

sonarqube-frontend-sast:
  stage: test
  image: sonarsource/sonar-scanner-cli
  script:
    - sonar-scanner $SONAR_FRONT_OPTS
  allow_failure: false

release:
  stage: release
  script:
    - tar czvf sausage-store-${VERSION}.tar.gz -C frontend/dist .
    - echo ${NEXUS_REPO_URL} ${NEXUS_REPO_FRONTEND_NAME} ${VERSION}
    - >
      curl -v -u "${NEXUS_REPO_USER}:${NEXUS_REPO_PASS}"
      --upload-file sausage-store-${VERSION}.tar.gz
      ${NEXUS_REPO_URL}/repository/${NEXUS_REPO_FRONTEND_NAME}/${VERSION}/sausage-store-${VERSION}.tar.gz
  only:
    changes:
      - frontend/**/*

deploy:
  stage: deploy
  before_script:
    #устанавливаем ssh-agent для удобства аутентификации по ssh
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
      #сохраняем сгенеренный ранее приватный ключ для раннера
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 600 ~/.ssh
    - ssh-keyscan ${DEV_HOST} >> ~/.ssh/known_hosts
    # Копируем файл сервиса на сервер
  script:
    - ssh ${DEV_USER}@${DEV_HOST} "export "CURRENT_VERSION=${VERSION}"; export "VERSION=${VERSION}"; export "DEV_HOST=${DEV_HOST}";export "NEXUS_REPO_URL=${NEXUS_REPO_URL}"; export "NEXUS_REPO_FRONTEND_NAME=${NEXUS_REPO_FRONTEND_NAME}"; export "NEXUS_REPO_USER=${NEXUS_REPO_USER}"; export "NEXUS_REPO_PASS=${NEXUS_REPO_PASS}";setsid /bin/bash -s " < ./frontend/deploy.sh
  environment:
    name: staging
    url: http://std-ext-019-01.praktikum-services.tech

#telegram-notification-frontend:
#  stage: notify
#  rules:
#    - changes:
#      - frontend/**/*
#    - if: '$CI_COMMIT_MESSAGE =~ /send notification/i'
#      when: always
#    - when: never
#  script:
#    - |
#      curl -s -X POST -H "Content-Type: application/json" \
#      -d '{"chat_id": "-1002426676593", "text": "✅ Быковский Д.В. Frontend успешно собран! Ссылка на артефакт: '$CI_PROJECT_URL'/-/jobs/artifacts/'$CI_COMMIT_SHA'/download?job=build-frontend-code-job"}' \
#      "https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage"