services:
  frontend:
    image: ${CI_REGISTRY_IMAGE}/sausage-frontend:${VERSION}
    container_name: sausage-frontend
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ~/frontend/templates:/etc/docker-gen/templates
    environment:
      - VIRTUAL_HOST=backend
    command: >
      sh -c "
      ACTIVE_BACKEND=sausage-backend-${DEPLOY_COLOR};
      until docker inspect -f {{.State.Health.Status}} $ACTIVE_BACKEND | grep healthy; do sleep 5; done;
      docker-gen -watch -notify 'nginx -s reload'
      /etc/docker-gen/templates/default.conf.tmpl
      /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    networks:
      - sausage_network

networks:
  sausage_network:
    driver: bridge