spring:
  datasource:
    url: jdbc:postgresql://rc1d-78co8isdqitugh45.mdb.yandexcloud.net:6432/std-ext-019-01
    username: std-ext-019-01
    password: Testusr1234
    driver-class-name: org.postgresql.Driver
  
  data:
    mongodb:
      uri: mongodb://std-ext-019-01:Testusr1234@rc1d-9f1992i4l77794td.mdb.yandexcloud.net:27018/db?replicaSet=rs01&tls=true

app:
  deployment:
    color: blue
    version: ${VERSION}