spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

spring.security:
  enabled: false