spring.application.name=sausage-store
management.security.enabled=false

#spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://rc1d-78co8isdqitugh45.mdb.yandexcloud.net:6432/?sslmode=verify-full&target_session_attrs=read-write
#spring.datasource.username=std-ext-019-27 #переключено в Vault
#spring.datasource.password=Testusr1234	#уже было закоментировано, но так же передано в Vault
# Пароль удалён из конфига для безопасности

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Токен для подключения к Vault
spring.cloud.vault.token=hvs.7MU26s5lDFxQitAejlg3CsED
# Протокол доступа к API Vault (в проде лучше использовать https)
spring.cloud.vault.scheme=http
spring.cloud.vault.host=std-ext-019-27.praktikum-services.tech
spring.cloud.vault.kv.enabled=true
spring.config.import=vault://secret/${spring.application.name}/

